name: Build Contracts

on:
  push:
    branches: ["blockchain"]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./blockchain/on-chain
    steps:
      - uses: actions/checkout@v3
      - uses: aiken-lang/setup-aiken@v1
        with:
          version: v1.1.16
      - run: aiken fmt --check
      - run: aiken check -D
      - run: aiken build
